# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines

pool:
  # vmImage: ubuntu-latest
  name: PiG Agents

steps:
#- script: echo ${{ resources.repositories['self'].name }}

- script: |
    echo "Logging Repository Information"
    
#     # Log all properties of self repository
#     if ($(Build.Repository.Id) -ne '') {
#       echo "Repository Id: $(Build.Repository.Id)"
# #        echo "Repository Name: $(Build.Repository.Name)"
# #        echo "Repository Type: $(Build.Repository.Provider)"
# #        echo "Repository URL: $(Build.Repository.Uri)"
# #        echo "Repository Branch: $(Build.SourceBranch)"
# #        # Add more properties as needed
#     } else {
#       echo "Self repository information not available."
#     }
# displayName: 'Log Repository Info'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
